import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1-1",
    name: "White Mug",
    category: "Mugs",
    price: 149,
    cardImage: "/bannerimg/1 (1).jpeg",
    image: "/showimg/1 (1).jpeg",
    description: "Classic white ceramic mug with your custom print. Perfect for office and home use.",
    specs: "Capacity: 330ml | Material: Ceramic | Dishwasher Safe",
    printAreaWidth: 200, printAreaHeight: 120, printAreaX: 80, printAreaY: 60,
  },
  {
    id: "1-2",
    name: "Patch Mug",
    category: "Mugs",
    price: 249,
    cardImage: "/bannerimg/1 (2).jpeg",
    image: "/showimg/1 (2).jpeg",
    description: "Premium patch mug with a raised custom print area for a unique 3D look.",
    specs: "Capacity: 350ml | Material: Ceramic | Premium Finish",
    printAreaWidth: 180, printAreaHeight: 100, printAreaX: 90, printAreaY: 70,
  },
  {
    id: "1-3",
    name: "Mini Mug",
    category: "Mugs",
    price: 129,
    cardImage: "/bannerimg/1 (3).jpeg",
    image: "/showimg/1 (3).jpeg",
    description: "Adorable mini mug, great for espresso or as a decorative keepsake.",
    specs: "Capacity: 150ml | Material: Ceramic | Cute & Compact",
    printAreaWidth: 140, printAreaHeight: 90, printAreaX: 70, printAreaY: 55,
  },
  {
    id: "1-4",
    name: "Magic Mug",
    category: "Mugs",
    price: 299,
    cardImage: "/bannerimg/1 (4).jpeg",
    image: "/showimg/1 (4).jpeg",
    description: "Heat-sensitive magic mug — image appears when hot liquid is poured.",
    specs: "Capacity: 330ml | Heat Reactive | Temperature Sensitive Print",
    printAreaWidth: 200, printAreaHeight: 120, printAreaX: 80, printAreaY: 60,
  },
  {
    id: "1-5",
    name: "Sipper Bottle (750ml)",
    category: "Bottles",
    price: 299,
    cardImage: "/bannerimg/1 (5).jpeg",
    image: "/showimg/1 (5).jpeg",
    description: "Large 750ml sipper bottle with full-color custom print. BPA-free and leak-proof.",
    specs: "Capacity: 750ml | BPA Free | Leak Proof | Stainless Steel",
    printAreaWidth: 160, printAreaHeight: 200, printAreaX: 80, printAreaY: 40,
  },
  {
    id: "1-6",
    name: "Nozzle Bottle",
    category: "Bottles",
    price: 380,
    cardImage: "/bannerimg/1 (6).jpeg",
    image: "/showimg/1 (6).jpeg",
    description: "Sports nozzle bottle with ergonomic grip and your custom design.",
    specs: "Capacity: 600ml | Nozzle Cap | BPA Free | Sports Grade",
    printAreaWidth: 150, printAreaHeight: 180, printAreaX: 85, printAreaY: 50,
  },
  {
    id: "1-7",
    name: "Sipper Bottle (600ml)",
    category: "Bottles",
    price: 249,
    cardImage: "/bannerimg/1 (7).jpeg",
    image: "/showimg/1 (7).jpeg",
    description: "Compact 600ml sipper bottle, perfect for daily use with a vivid custom print.",
    specs: "Capacity: 600ml | Sipper Cap | BPA Free | Lightweight",
    printAreaWidth: 150, printAreaHeight: 180, printAreaX: 85, printAreaY: 50,
  },
  {
    id: "1-8",
    name: "Mouse Pad",
    category: "Accessories",
    price: 119,
    cardImage: "/bannerimg/1 (8).jpeg",
    image: "/showimg/1 (8).jpg",
    description: "Custom printed mouse pad with non-slip rubber base and smooth fabric surface.",
    specs: "Size: 25x21cm | Thickness: 3mm | Non-Slip Base | Waterproof",
    printAreaWidth: 260, printAreaHeight: 220, printAreaX: 20, printAreaY: 20,
  },
  {
    id: "1-9",
    name: "Sports Bottle",
    category: "Bottles",
    price: 349,
    cardImage: "/bannerimg/1 (9).jpeg",
    image: "/showimg/1 (9).jpeg",
    description: "Premium sports bottle designed for active lifestyles with bold custom graphics.",
    specs: "Capacity: 700ml | Stainless Steel | Double-Wall Insulated",
    printAreaWidth: 160, printAreaHeight: 200, printAreaX: 80, printAreaY: 40,
  },
  {
    id: "1-10",
    name: "Black T-Shirt",
    category: "T-Shirts",
    price: 390,
    cardImage: "/bannerimg/1 (10).jpeg",
    image: "/showimg/1 (10).jpeg",
    description: "Premium 200gsm black cotton t-shirt with your custom front print.",
    specs: "GSM: 200 | Material: 100% Cotton | Unisex Fit | S–3XL",
    printAreaWidth: 220, printAreaHeight: 260, printAreaX: 90, printAreaY: 80,
  },
  {
    id: "1-11",
    name: "Orange T-Shirt",
    category: "T-Shirts",
    price: 379,
    cardImage: "/bannerimg/1 (11).jpeg",
    image: "/showimg/1 (11).jpeg",
    description: "Vibrant 200gsm orange cotton t-shirt — stand out with your custom design.",
    specs: "GSM: 200 | Material: 100% Cotton | Unisex Fit | S–3XL",
    printAreaWidth: 220, printAreaHeight: 260, printAreaX: 90, printAreaY: 80,
  },
  {
    id: "1-12",
    name: "White T-Shirt",
    category: "T-Shirts",
    price: 449,
    cardImage: "/bannerimg/1 (12).jpeg",
    image: "/showimg/1 (12).jpeg",
    description: "High-quality 220gsm white t-shirt, ideal for full-color prints.",
    specs: "GSM: 220 | Material: 100% Cotton | Premium Grade | S–3XL",
    printAreaWidth: 220, printAreaHeight: 260, printAreaX: 90, printAreaY: 80,
  },
  {
    id: "1-13",
    name: "Brown T-Shirt",
    category: "T-Shirts",
    price: 339,
    cardImage: "/bannerimg/1 (13).jpeg",
    image: "/showimg/1 (13).jpeg",
    description: "Earthy 160gsm brown t-shirt with custom print for a casual aesthetic.",
    specs: "GSM: 160 | Material: 100% Cotton | Casual Fit | S–3XL",
    printAreaWidth: 220, printAreaHeight: 260, printAreaX: 90, printAreaY: 80,
  },
  {
    id: "1-14",
    name: "White Hoodie",
    category: "Hoodies",
    price: 749,
    cardImage: "/bannerimg/1 (14).jpeg",
    image: "/showimg/1 (14).jpeg",
    description: "Premium 400gsm white hoodie with your custom design — thick and cozy.",
    specs: "GSM: 400 | Material: Cotton-Fleece Blend | Kangaroo Pocket | S–3XL",
    printAreaWidth: 230, printAreaHeight: 280, printAreaX: 85, printAreaY: 100,
  },
  {
    id: "1-15",
    name: "Blue Hoodie",
    category: "Hoodies",
    price: 549,
    cardImage: "/bannerimg/1 (15).jpeg",
    image: "/showimg/1 (15).jpeg",
    description: "350gsm blue hoodie, perfect for cold days with a personal touch.",
    specs: "GSM: 350 | Material: Cotton-Fleece Blend | Ribbed Cuffs | S–3XL",
    printAreaWidth: 230, printAreaHeight: 280, printAreaX: 85, printAreaY: 100,
  },
  {
    id: "1-16",
    name: "Chocolaty T-Shirt",
    category: "T-Shirts",
    price: 449,
    cardImage: "/bannerimg/1 (16).jpeg",
    image: "/showimg/1 (16).jpeg",
    description: "Rich chocolaty 240gsm t-shirt with premium custom print finish.",
    specs: "GSM: 240 | Material: 100% Cotton | Premium Fit | S–3XL",
    printAreaWidth: 220, printAreaHeight: 260, printAreaX: 90, printAreaY: 80,
  },
  {
    id: "1-17",
    name: "Black Hoodie",
    category: "Hoodies",
    price: 699,
    cardImage: "/bannerimg/1 (17).jpeg",
    image: "/showimg/1 (17).jpeg",
    description: "Sleek 350gsm black hoodie — minimal, bold, and fully customizable.",
    specs: "GSM: 350 | Material: Cotton-Fleece Blend | Slim Fit | S–3XL",
    printAreaWidth: 230, printAreaHeight: 280, printAreaX: 85, printAreaY: 100,
  },
];

export const categories = ["All", "Mugs", "Bottles", "T-Shirts", "Hoodies", "Accessories"];

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "All") return products;
  return products.filter((p) => p.category === category);
}
